format = """
$username\
$hostname\
$localip\
$shlvl\
$singularity\
$kubernetes\
$directory\
$vcsh\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$cmd_duration\ 
$fill\
$hg_branch\
$docker_context\
$package\
$c\
$cmake\
$cobol\
$daml\
$dart\
$deno\
$dotnet\
$elixir\
$elm\
$erlang\
$golang\
$guix_shell\
$haskell\
$haxe\
$helm\
$java\
$julia\
$kotlin\
$lua\
$nim\
$nodejs\
$ocaml\
$opa\
$perl\
$php\
$pulumi\
$purescript\
$python\
$raku\
$rlang\
$red\
$ruby\
$rust\
$scala\
$swift\
$terraform\
$vlang\
$vagrant\
$zig\
$buf\
$nix_shell\
$conda\
$meson\
$spack\
$memory_usage\
$aws\
$gcloud\
$openstack\
$azure\
$env_var\
$crystal\
$custom\
$sudo\
$jobs $time\
$line_break\
$battery\
$status\
$os\
$container\
$shell\
$character
"""

[line_break]
disabled = false
"$schema" = 'https://starship.rs/config-schema.json'
add_newline = true

[fill]
symbol = " "

[character]
# [ âœ , â¯, âœ , ğŸ‘‘, â¤­, â¤© ](grey, purple, bold red)
success_symbol = "[â¤­](purple)"
error_symbol = "[â¤©](bold red)"

[directory]
truncation_length = 2
truncate_to_repo = true

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

[git_status]
style='bold cyan'

[time]
disabled=true
time_format = "%H:%M"
style="bold cyan"
format="[$time]($style)"

[cmd_duration]
format="[$duration]($style)"

[php]
symbol = ' ğŸ˜'
format = "[\\[$symbol\\]](bold blue)"

[python]
symbol = ' îˆµ '
format = "[\\[$symbol\\]](bold green)"

[nodejs]
symbol = ' îœ˜ '
format = "[\\[$symbol\\]](bold yellow)"

[lua]
symbol = 'ğŸŒ™'
format = "[\\[$symbol\\]](bold blue)"


[rlang]
symbol = " ï³’ "
format = "[\\[$symbol\\]](bold blue)"

[ruby]
symbol = " î‘ "
format = "[\\[$symbol\\]](bold red)"

[rust]
symbol = " î¨ "
format = "[\\[$symbol\\]](bold white)"

[scala]
symbol = "îœ· Scala"
format = "[\\[$symbol\\]](bold red)"

[spack]
symbol = " ğŸ…¢ "
format = "[\\[$symbol\\]](bold yellow)"

[aws]
symbol = "îŒ½ aws"
format = "[\\[$symbol\\]](bold blue)"

[buf]
symbol = " ï’ "
format = "[\\[$symbol\\]](bold blue)"

[c]
symbol = " î˜ "
format = "[\\[$symbol\\]](bold blue)"

[conda]
symbol = "ï„Œ"
format = "[\\[$symbol\\]](bold blue)"

[dart]
symbol = " î˜ "
format = "[\\[$symbol\\]](bold blue)"

[docker_context]
symbol = " ïŒˆ "
format = "[\\[$symbol\\]](bold blue)"

[elixir]
symbol = " î‰µ "
format = "[\\[$symbol\\]](bold blue)"

[elm]
symbol = " î˜¬ "
format = "[\\[$symbol\\]](bold yellow)"

[golang]
symbol = "î˜§ go"
format = "[\\[$symbol\\]](bold white)"

[haskell]
symbol = " î· "
format = "[\\[$symbol\\]](bold blue)"

[java]
symbol = " î‰– "
format = "[\\[$symbol\\]](bold white)"

[julia]
symbol = " î˜¤ "
format = "[\\[$symbol\\]](bold red)"

[memory_usage]
symbol = " ï¡š "
format = "[\\[$symbol\\]](bold white)"

[nim]
symbol = " ïš¤ "
format = "[\\[$symbol\\]](bold white)"

[nix_shell]
symbol = " ïŒ“ "
format = "[\\[$symbol\\]](bold white)"

